package changelog

import (
	"cmp"
	"fmt"
	"slices"
	"strings"

	"github.com/evictedcucumber/packwiz/core"
	"github.com/evictedcucumber/packwiz/internal/ui"
)

// section is a heading in a release, and the changes listed under it
type section struct {
	title string
	has   func(Change) bool
}

func isKind(kinds ...Kind) func(Change) bool {
	return func(c Change) bool { return slices.Contains(kinds, c.Kind) }
}

// isConfig is a change to a config file, or a note about config
func isConfig(c Change) bool {
	return isKind(FileAdded, FileChanged, FileRemoved)(c) || (c.Kind == Note && c.Scope == "config")
}

var sections = []section{
	{"Added", isKind(ModAdded)},
	{"Updated", isKind(ModUpdated)},
	{"Removed", isKind(ModRemoved)},
	{"Config", isConfig},
	// Notes are what someone wrote about a change in their own words: whatever isn't about a mod or config
	{"Changes", func(c Change) bool { return c.Kind == Note && c.Scope != "config" }},
}

// RenderMarkdown renders the changelog for a list of releases (oldest first), with the newest release at the top.
func RenderMarkdown(releases []Release) string {
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString("All notable changes to this modpack are documented here.\n\n")
	b.WriteString("Generated by `packwiz changelog release`; edits made here are overwritten.\n")
	for i := len(releases) - 1; i >= 0; i-- {
		b.WriteString("\n")
		b.WriteString(RenderRelease(releases[i]))
	}
	return b.String()
}

// style decorates the parts of a release as it is rendered. The release that is printed to a terminal is coloured, and
// the Markdown that is saved is not: the zero style leaves everything as it is, and colouring never changes the text.
type style struct {
	colour bool
}

func (s style) apply(st ui.Style, text string) string {
	if !s.colour {
		return text
	}
	return st.Sprint(text)
}

func (s style) heading(text string) string    { return s.apply(ui.Bold, s.apply(ui.Info, text)) }
func (s style) subheading(text string) string { return s.apply(ui.Bold, text) }
func (s style) callout(text string) string    { return s.apply(ui.Warning, text) }
func (s style) name(text string) string       { return s.apply(ui.Bold, text) }
func (s style) code(text string) string       { return s.apply(ui.Info, text) }
func (s style) breaking(text string) string   { return s.apply(ui.Error, text) }
func (s style) side(text string) string       { return s.apply(ui.Muted, text) }

// removed is a version that was there before the release, and added one that is there after it
func (s style) removed(text string) string { return s.apply(ui.Error, text) }
func (s style) added(text string) string   { return s.apply(ui.Success, text) }

// RenderRelease renders one release as a Markdown section. Within each heading, mods that run on the server come
// first, as they are what makes a release major, and then everything is in alphabetical order.
func RenderRelease(r Release) string {
	return renderRelease(r, style{})
}

func renderRelease(r Release, st style) string {
	blocks := []string{st.heading(fmt.Sprintf("## %s - %s", r.Version, r.Date))}

	if r.IsInitial() {
		if summary := initialSummary(r.Changes); summary != "" {
			blocks = append(blocks, "Initial release with "+summary+".")
		}
	}
	if !r.IsInitial() && changesServer(r.Changes) {
		blocks = append(blocks, st.callout("> **Server update required.** This release changes mods that run on the server."))
	}

	for _, s := range sections {
		var changes []Change
		for _, c := range r.Changes {
			if s.has(c) {
				changes = append(changes, c)
			}
		}
		if len(changes) == 0 {
			continue
		}
		slices.SortStableFunc(changes, compareChanges)

		lines := make([]string, len(changes))
		for i, c := range changes {
			lines[i] = "- " + describeStyled(c, st)
		}
		blocks = append(blocks, st.subheading("### "+s.title)+"\n\n"+strings.Join(lines, "\n"))
	}
	return strings.Join(blocks, "\n\n") + "\n"
}

// changesServer reports whether any of the changes is to a mod that runs on the server.
func changesServer(changes []Change) bool {
	for _, c := range changes {
		if c.IsMod() && RunsOnServer(c.Side) {
			return true
		}
	}
	return false
}

// compareChanges orders changes within a heading: mods that run on the server first, then by name, then by path. Notes
// come after files, and stay in the order they were made.
func compareChanges(a, b Change) int {
	if aNote, bNote := a.Kind == Note, b.Kind == Note; aNote || bNote {
		switch {
		case aNote && bNote:
			return 0
		case aNote:
			return 1
		default:
			return -1
		}
	}
	if a.IsMod() && b.IsMod() {
		if serverA, serverB := RunsOnServer(a.Side), RunsOnServer(b.Side); serverA != serverB {
			if serverA {
				return -1
			}
			return 1
		}
		if c := cmp.Compare(strings.ToLower(a.Name), strings.ToLower(b.Name)); c != 0 {
			return c
		}
	}
	return cmp.Compare(a.Path, b.Path)
}

// initialSummary counts what a pack's first release contains, e.g. "12 mods and 3 config files".
func initialSummary(changes []Change) string {
	mods := 0
	for _, c := range changes {
		if c.IsMod() {
			mods++
		}
	}
	files := len(changes) - mods

	var parts []string
	if mods > 0 {
		parts = append(parts, fmt.Sprintf("%d %s", mods, plural(mods, "mod")))
	}
	if files > 0 {
		parts = append(parts, fmt.Sprintf("%d %s", files, plural(files, "config file")))
	}
	return strings.Join(parts, " and ")
}

func plural(n int, noun string) string {
	if n == 1 {
		return noun
	}
	return noun + "s"
}

// describe summarises a change on one line, e.g. "**Sodium** 0.5.7 → 0.5.8 (client)"
func describe(c Change) string {
	return describeStyled(c, style{})
}

func describeStyled(c Change, st style) string {
	switch c.Kind {
	case FileAdded:
		return "Added " + st.code("`"+c.Path+"`")
	case FileChanged:
		return "Changed " + st.code("`"+c.Path+"`")
	case FileRemoved:
		return "Removed " + st.code("`"+c.Path+"`")
	case Note:
		text := escapeMarkdown(c.Text)
		if c.Scope != "" && c.Scope != "config" {
			text = st.name("**"+escapeMarkdown(c.Scope)+":**") + " " + text
		}
		if c.Breaking {
			text = st.breaking("**Breaking:**") + " " + text
		}
		return text
	}

	parts := []string{st.name("**" + escapeMarkdown(c.Name) + "**")}
	switch {
	case c.From != "" && c.To != "":
		parts = append(parts, st.removed(escapeMarkdown(c.From))+" → "+st.added(escapeMarkdown(c.To)))
	case c.To != "":
		parts = append(parts, st.added(escapeMarkdown(c.To)))
	case c.From != "":
		parts = append(parts, st.removed(escapeMarkdown(c.From)))
	}
	parts = append(parts, st.side("("+sideLabel(c.Side)+")"))
	return strings.Join(parts, " ")
}

// sideLabel says where a mod runs, in words a player would use rather than packwiz's "both".
func sideLabel(side string) string {
	switch side {
	case core.ClientSide:
		return "client"
	case core.ServerSide:
		return "server"
	default:
		return "client + server"
	}
}

var markdownEscaper = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", `*`, `\*`, `_`, `\_`, `[`, `\[`, `]`, `\]`, `<`, `\<`, `>`, `\>`,
)

// escapeMarkdown stops a mod's name or version, which come from whoever published it, from being read as formatting.
func escapeMarkdown(s string) string {
	return markdownEscaper.Replace(s)
}
