package changelog

import (
	"fmt"
	"strings"
)

// section is a heading in a release, and the kinds of change listed under it
type section struct {
	title string
	kinds []Kind
}

var sections = []section{
	{"Added", []Kind{ModAdded}},
	{"Removed", []Kind{ModRemoved}},
	{"Updated", []Kind{ModUpdated}},
	{"Config", []Kind{FileAdded, FileChanged, FileRemoved}},
}

// RenderMarkdown renders the changelog for a list of releases (oldest first), with the newest release at the top.
func RenderMarkdown(releases []Release) string {
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString("Generated by `packwiz changelog release`; any edits made here will be overwritten.\n")
	for i := len(releases) - 1; i >= 0; i-- {
		b.WriteString("\n")
		b.WriteString(RenderRelease(releases[i]))
	}
	return b.String()
}

// RenderRelease renders one release as a Markdown section.
func RenderRelease(r Release) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## %s - %s\n", r.Version, r.Date)
	if r.Bump == BumpMajor {
		b.WriteString("\n> This release changes mods that run on the server; servers must be updated to match.\n")
	}

	for _, s := range sections {
		var lines []string
		for _, c := range r.Changes {
			if containsKind(s.kinds, c.Kind) {
				lines = append(lines, "- "+describe(c))
			}
		}
		if len(lines) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n### %s\n\n%s\n", s.title, strings.Join(lines, "\n"))
	}
	return b.String()
}

func containsKind(kinds []Kind, kind Kind) bool {
	for _, k := range kinds {
		if k == kind {
			return true
		}
	}
	return false
}

// describe summarises a change on one line, e.g. "**Sodium** 0.5.7 → 0.5.8 (client)"
func describe(c Change) string {
	switch c.Kind {
	case FileAdded:
		return fmt.Sprintf("Added `%s`", c.Path)
	case FileChanged:
		return fmt.Sprintf("Changed `%s`", c.Path)
	case FileRemoved:
		return fmt.Sprintf("Removed `%s`", c.Path)
	}

	parts := []string{"**" + c.Name + "**"}
	switch {
	case c.From != "" && c.To != "":
		parts = append(parts, c.From+" → "+c.To)
	case c.To != "":
		parts = append(parts, c.To)
	case c.From != "":
		parts = append(parts, c.From)
	}
	side := c.Side
	if side == "" {
		side = "both"
	}
	parts = append(parts, "("+side+")")
	return strings.Join(parts, " ")
}
