package changelog

import (
	"cmp"
	"fmt"
	"slices"
	"strings"

	"github.com/evictedcucumber/packwiz/core"
)

// section is a heading in a release, and the kinds of change listed under it
type section struct {
	title string
	kinds []Kind
}

var sections = []section{
	{"Added", []Kind{ModAdded}},
	{"Updated", []Kind{ModUpdated}},
	{"Removed", []Kind{ModRemoved}},
	{"Config", []Kind{FileAdded, FileChanged, FileRemoved}},
}

// RenderMarkdown renders the changelog for a list of releases (oldest first), with the newest release at the top.
func RenderMarkdown(releases []Release) string {
	var b strings.Builder
	b.WriteString("# Changelog\n\n")
	b.WriteString("All notable changes to this modpack are documented here.\n\n")
	b.WriteString("Generated by `packwiz changelog release`; edits made here are overwritten.\n")
	for i := len(releases) - 1; i >= 0; i-- {
		b.WriteString("\n")
		b.WriteString(RenderRelease(releases[i]))
	}
	return b.String()
}

// RenderRelease renders one release as a Markdown section. Within each heading, mods that run on the server come
// first, as they are what makes a release major, and then everything is in alphabetical order.
func RenderRelease(r Release) string {
	blocks := []string{fmt.Sprintf("## %s - %s", r.Version, r.Date)}

	if r.IsInitial() {
		if summary := initialSummary(r.Changes); summary != "" {
			blocks = append(blocks, "Initial release with "+summary+".")
		}
	}
	if r.Bump == BumpMajor {
		blocks = append(blocks, "> **Server update required.** This release changes mods that run on the server.")
	}

	for _, s := range sections {
		var changes []Change
		for _, c := range r.Changes {
			if slices.Contains(s.kinds, c.Kind) {
				changes = append(changes, c)
			}
		}
		if len(changes) == 0 {
			continue
		}
		slices.SortFunc(changes, compareChanges)

		lines := make([]string, len(changes))
		for i, c := range changes {
			lines[i] = "- " + describe(c)
		}
		blocks = append(blocks, "### "+s.title+"\n\n"+strings.Join(lines, "\n"))
	}
	return strings.Join(blocks, "\n\n") + "\n"
}

// compareChanges orders changes within a heading: mods that run on the server first, then by name, then by path.
func compareChanges(a, b Change) int {
	if a.IsMod() && b.IsMod() {
		if serverA, serverB := RunsOnServer(a.Side), RunsOnServer(b.Side); serverA != serverB {
			if serverA {
				return -1
			}
			return 1
		}
		if c := cmp.Compare(strings.ToLower(a.Name), strings.ToLower(b.Name)); c != 0 {
			return c
		}
	}
	return cmp.Compare(a.Path, b.Path)
}

// initialSummary counts what a pack's first release contains, e.g. "12 mods and 3 config files".
func initialSummary(changes []Change) string {
	mods := 0
	for _, c := range changes {
		if c.IsMod() {
			mods++
		}
	}
	files := len(changes) - mods

	var parts []string
	if mods > 0 {
		parts = append(parts, fmt.Sprintf("%d %s", mods, plural(mods, "mod")))
	}
	if files > 0 {
		parts = append(parts, fmt.Sprintf("%d %s", files, plural(files, "config file")))
	}
	return strings.Join(parts, " and ")
}

func plural(n int, noun string) string {
	if n == 1 {
		return noun
	}
	return noun + "s"
}

// describe summarises a change on one line, e.g. "**Sodium** 0.5.7 → 0.5.8 (client)"
func describe(c Change) string {
	switch c.Kind {
	case FileAdded:
		return fmt.Sprintf("Added `%s`", c.Path)
	case FileChanged:
		return fmt.Sprintf("Changed `%s`", c.Path)
	case FileRemoved:
		return fmt.Sprintf("Removed `%s`", c.Path)
	}

	parts := []string{"**" + escapeMarkdown(c.Name) + "**"}
	switch {
	case c.From != "" && c.To != "":
		parts = append(parts, escapeMarkdown(c.From)+" → "+escapeMarkdown(c.To))
	case c.To != "":
		parts = append(parts, escapeMarkdown(c.To))
	case c.From != "":
		parts = append(parts, escapeMarkdown(c.From))
	}
	parts = append(parts, "("+sideLabel(c.Side)+")")
	return strings.Join(parts, " ")
}

// sideLabel says where a mod runs, in words a player would use rather than packwiz's "both".
func sideLabel(side string) string {
	switch side {
	case core.ClientSide:
		return "client"
	case core.ServerSide:
		return "server"
	default:
		return "client + server"
	}
}

var markdownEscaper = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", `*`, `\*`, `_`, `\_`, `[`, `\[`, `]`, `\]`, `<`, `\<`, `>`, `\>`,
)

// escapeMarkdown stops a mod's name or version, which come from whoever published it, from being read as formatting.
func escapeMarkdown(s string) string {
	return markdownEscaper.Replace(s)
}
