package changelog

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/evictedcucumber/packwiz/core"
)

// ServerMarkdownFile is the server's changelog: MarkdownFile with only what changes the server, in the server pack's
// folder (core.ServerConfigDir), so that the server pack has it in place of the pack's own. It is written with
// MarkdownFile, from the same releases, whenever the pack has that folder. It is a path relative to the pack's folder,
// with forward slashes.
const ServerMarkdownFile = core.ServerConfigDir + "/" + MarkdownFile

// serverMarkdownTitle starts the server's changelog
const serverMarkdownTitle = "# Server Changelog\n"

// OnServer reports whether a change is to what a server runs: anything but a mod that is only on the client. Config files
// and notes are, as the server pack has every config file, and a note says nothing of where it applies.
func OnServer(c Change) bool {
	return !c.IsMod() || RunsOnServer(c.Side)
}

// serverChanges are the changes that are OnServer, in a new slice.
func serverChanges(changes []Change) []Change {
	var server []Change
	for _, c := range changes {
		if OnServer(c) {
			server = append(server, c)
		}
	}
	return server
}

// RenderServerMarkdown is RenderMarkdownWithUnreleased for the server: each release with only its changes that are
// OnServer. Every release is listed, so the server's changelog has the pack's versions, and one that changes nothing on
// the server says so, which tells whoever runs it that the server needn't be updated for it.
func RenderServerMarkdown(releases []Release, unreleased []Change) string {
	var b strings.Builder
	b.WriteString(serverMarkdownTitle + "\n")
	b.WriteString("All notable changes to this modpack's server are documented here. Mods that are only on the client are left out.\n\n")
	b.WriteString("Generated by `packwiz changelog release`; edits made here are overwritten.\n")
	if unreleased = serverChanges(unreleased); len(unreleased) > 0 {
		b.WriteString("\n")
		b.WriteString(renderChanges("## Unreleased", Release{Bump: BumpMinor, Changes: unreleased}, style{}))
	}
	b.WriteString(renderServerReleases(releases))
	return b.String()
}

// renderServerReleases is the releases of the server's changelog, newest first, each after a blank line
func renderServerReleases(releases []Release) string {
	var b strings.Builder
	for i := len(releases) - 1; i >= 0; i-- {
		r := releases[i]
		r.Changes = serverChanges(r.Changes)
		b.WriteString("\n")
		if len(r.Changes) == 0 && !r.IsInitial() {
			b.WriteString("## " + r.Version + " - " + r.Date + "\n\nNothing in this release changes the server.\n")
			continue
		}
		b.WriteString(RenderRelease(r))
	}
	return b.String()
}

// ServerMarkdownIsCurrent reports whether the text of a server's changelog has the releases as RenderServerMarkdown
// renders them now, whatever it lists as unreleased above them.
func ServerMarkdownIsCurrent(text string, releases []Release) bool {
	return strings.HasPrefix(text, serverMarkdownTitle) && strings.HasSuffix(text, renderServerReleases(releases))
}

// HasServerPack reports whether the pack in the folder packRoot has a server pack, and so a changelog of its own for the
// server: whether it has the folder of the server pack's files (core.ServerConfigDir).
func HasServerPack(packRoot string) bool {
	info, err := os.Stat(filepath.Join(packRoot, core.ServerConfigDir))
	return err == nil && info.IsDir()
}

// serverMarkdownPath is where the server's changelog is written
func serverMarkdownPath() string {
	return filepath.Join(packRoot(), filepath.FromSlash(ServerMarkdownFile))
}

// writeServerMarkdown writes the server's changelog if the pack has a server pack, and says whether it did
func writeServerMarkdown(releases []Release, unreleased []Change) (bool, error) {
	if !HasServerPack(packRoot()) {
		return false, nil
	}
	if err := writeFileAtomic(serverMarkdownPath(), []byte(RenderServerMarkdown(releases, unreleased))); err != nil {
		return false, fmt.Errorf("failed to write %s: %w", ServerMarkdownFile, err)
	}
	return true, nil
}
